### ISSUE TITLE
Cannot run rake db:drop

### ISSUE THREAD

**Issue by hysan** [learn-co-curriculum/activerecord-costume-store-todo#63]
If a student wants to blow away all their changes using `rake db:drop`, they cannot as they will get this error:

```
// ♥ rake db:drop
rake aborted!
NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails
/Users/hcheng/.rvm/gems/ruby-2.3.3/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:101:in `env'
/Users/hcheng/.rvm/gems/ruby-2.3.3/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:160:in `drop_current'
/Users/hcheng/.rvm/gems/ruby-2.3.3/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/hcheng/.rvm/gems/ruby-2.3.3/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:40:in `block (2 levels) in <top (required)>'
/Users/hcheng/.rvm/gems/ruby-2.3.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/hcheng/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/hcheng/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
```

**Comment by cjbrock** [comment]
Hi @hysan! This can be solved by using `bundle exec rake db:drop`. 

// <3 Corinna
